version: "3"
services:
  backend:
    image:  des0/app:latest
    container_name: app
    env_file: my_vars.env
    depends_on:
      - db

  web:
    image: des0/web:latest 
    env_file: my_vars.env
    ports:
      - 8080:80
    expose:
      - 8080
    depends_on:
      - backend
      - db
  db:
    image: mysql
    container_name: mysql_db
    env_file: my_vars.env


  